server:
  port: 8083

spring:
  cloud:
    function:
      definition: processDocument # The name of the Java function bean
    stream:
      bindings:
        processDocument-in-0:
          destination: document-exchange
          group: ai-processor-group
          content-type: application/json
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  ai:
    google:
      genai:
        api-key: 
      chat:
          options:
            model: gemini-1.5-flash

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

storage:
  bucket: documents-bucket
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin

logging:
  level:
    org.springframework.cloud.stream: DEBUG

document-service:
  url: http://localhost:8081/api/documents
