server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
            lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
##Disable case              

management:
  endpoints:
    web:
      exposure:
        include: "*" 

logging:
  level:
    # Spring Security resource-server internals
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.security.oauth2.server.resource.authentication: DEBUG
    org.springframework.security.oauth2.server.resource.web: DEBUG

    # General Spring Security
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG

    # Nimbus internals involved in JWK retrieval/selection/verification
    com.nimbusds.jose: DEBUG
    com.nimbusds.jose.jwk: DEBUG
    com.nimbusds.jose.jwk.source: DEBUG
    com.nimbusds.jose.proc: DEBUG

    # Reactive HTTP client used to fetch JWKS
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG   
