server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insight_auth_db
    username: root
    password: root

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 3e1649e7937351b012e5f0199c1cda4e817a55400f8c03b7491c24c32d6a0352
  expiration-seconds: 15
  keystore:
    path: D:\Utkarsh\Microservices\SecurityCert\jwt.p12   # path to your p12
    store-password: ${JWT_KEYSTORE_PASSWORD:me@#23}
    key-alias: jwt
    key-password: ${JWT_KEY_PASSWORD:me@#23}

management:
  endpoints:
    web:
      exposure:
        include: "*" 

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security: DEBUG
    com.nimbusds.jose: DEBUG        
