server:
  port: 8084

spring:
  elasticsearch:
    uris: http://localhost:9200
    socket-timeout: 10s
  
  cloud:
    function:
      definition: indexDocument
    stream:
      bindings:
        indexDocument-in-0:
          destination: search-exchange
          group: search-service-group
          content-type: application/json

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
